name: Aftenposten
favicon: null
layout_spectrum: 0.5135135906748474
typography_spectrum: 0.38385107461363077
title: Aftenposten The Grid Playground
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.23601266834884882
  lightness: 0.6755606166552752
  saturation: 0.4342289993073791
  rhythmicContrast: 0.6787349057849497
purpose: []
